name: CI - [Project] Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Configuring Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Environment setup
        run: make install

      - name: Running unit tests
        run: make test

      - name: Running strict linting
        run: make lint-strict
